name: flutter_blue_plus_example
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.28.0
  syncfusion_flutter_charts: ^24.1.47+2

flutter:
  uses-material-design: true
